go-dev:
	cd go && go run alipay_strategy.go wechat_pay_strategy.go pay_strategy.go pay_context.go main.go

java-dev:
	cd java && javac -d . *.java && java main.Main

clear-java:
	@cd java && rm -rf main
