
// Code generated by dynamic_proxy_generator.go. DO NOT EDIT.
package main

import "fmt"

// DynamicGenerateProxy 代理类
type DynamicGenerateProxy struct {
    target IUserService
}

// NewDynamicGenerateProxy 创建代理实例
func NewDynamicGenerateProxy(target IUserService) IUserService {
    return &DynamicGenerateProxy{target: target}
}

// PreHandler 前置处理
func (p *DynamicGenerateProxy) PreHandler(method string, args ...interface{}) {
    fmt.Printf("Before calling %s with args: %v\n", method, args)
}

// PostHandler 后置处理
func (p *DynamicGenerateProxy) PostHandler(method string, args ...interface{}) {
    fmt.Printf("After calling %s with args: %v\n", method, args)
}

// GetUser 代理方法
func (p *DynamicGenerateProxy) GetUser(name string) (*User, error) {
    // 前置处理
    p.PreHandler("GetUser", name)
    defer p.PostHandler("GetUser", name)

    // 调用目标方法
    return p.target.GetUser(name)
}
