go-dev:
	cd go && go run base_config_loader.go json_config_loader.go yaml_config_loader.go config_loader.go main.go

java-dev:
	cd java && javac -d . *.java && java main.Main

clear-java:
	@cd java && rm -rf main
