go-dev:
	cd go && go run main.go models.go simple_factory.go factory_method.go abstract_factory.go 

java-dev:
	cd java && javac -d . *.java && java main.Main

clear-java:
	@cd java && rm -rf main

java-ioc-dev:
	cd java/ioc && javac -d . *.java && java ioc.Main

clear-java-ioc:
	@cd java-ioc && rm -rf main
