go-dev:
	cd go && go run main.go builder.go models.go options.go

java-dev:
	cd java && javac -d . *.java && java main.Main

clear-java:
	@cd java && rm -rf main

java-ioc-dev:
	cd java/ioc && javac -d . *.java && java ioc.Main

clear-java-ioc:
	@cd java-ioc && rm -rf main
